AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  DisabledByDefault: true
  Exclude:
    - 'gemfiles/**/vendor/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/generators/**/templates/**/*'

Lint:
  Enabled: true
