AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  DisabledByDefault: true
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/**/vendor/**/*'
    - 'lib/generators/**/templates/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-rake

Lint:
  Enabled: true
