rvm:
#  - 1.9.3
#  - 2.1.2
  - 2.2.3
cache: bundler
notifications:
  email: false
sudo: false
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
script: appraisal rake test
