rvm:
  - 1.9.3
  - 2.1.2
  - 2.2.3
cache: bundler
notifications:
  email: false
sudo: false
script: 
 - bundle exec rake test
env:
 - "RAILS_VERSION="3.2.22"
 - "RAILS_VERSION="4.2.4"
 - "RAILS_VERSION="master"
