name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.6.5']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        bundler: 1.17.3
    - name: Install appraisal gems
      run: bundle exec appraisal install
    - name: Run appraisal tests
      run: bundle exec appraisal rake test
