name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: "2.6.10"
            bundler: "1.17.3"
            appraisals: "rails-4"
            experimental: false
          - ruby-version: "2.7.8"
            bundler: "2.4.22"
            appraisals: "rails-5"
            experimental: false
          - ruby-version: "3.0.7"
            bundler: "2.5.10"
            appraisals: "rails-6"
            experimental: false
          - ruby-version: "3.1.7"
            bundler: "2.5.10"
            appraisals: "rails-6 rails-7"
            experimental: false
          - ruby-version: "3.2.9"
            bundler: "2.5.10"
            appraisals: "rails-6 rails-7 rails-8 rails-edge"
            experimental: false
          - ruby-version: "3.3.9"
            bundler: "2.5.10"
            appraisals: "rails-6 rails-7 rails-8 rails-edge"
            experimental: false
          - ruby-version: "3.4.7"
            bundler: "2.5.10"
            appraisals: "rails-7 rails-8 rails-edge"
            experimental: false
          - ruby-version: "3.5.0-preview1"
            bundler: "2.5.10"
            appraisals: "rails-7 rails-8 rails-edge"
            experimental: false
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true
      - name: Install appraisal gems
        shell: bash
        run: |
          set -euo pipefail
          APPRAISALS="${{ matrix.appraisals }}"
          DEFAULT_BUNDLER="${{ matrix.bundler }}"
          for appraisal in $APPRAISALS; do
            if [ "$appraisal" = "rails-4" ]; then
              BUNDLER_VERSION="1.17.3"
            else
              BUNDLER_VERSION="$DEFAULT_BUNDLER"
            fi
            echo "Installing gems for ${appraisal} with bundler ${BUNDLER_VERSION}"
            bundle _${BUNDLER_VERSION}_ exec appraisal "${appraisal}" bundle install
          done
      - name: Run appraisal tests
        shell: bash
        run: |
          set -euo pipefail
          APPRAISALS="${{ matrix.appraisals }}"
          DEFAULT_BUNDLER="${{ matrix.bundler }}"
          for appraisal in $APPRAISALS; do
            if [ "$appraisal" = "rails-4" ]; then
              BUNDLER_VERSION="1.17.3"
            else
              BUNDLER_VERSION="$DEFAULT_BUNDLER"
            fi
            echo "Running tests for ${appraisal} with bundler ${BUNDLER_VERSION}"
            bundle _${BUNDLER_VERSION}_ exec appraisal "${appraisal}" rake test
          done
